INSERT INTO `admin` (`id`,`child_name`)
VALUES
	(1, NULL);
INSERT INTO `station` (`id`,`location`,`child_name`)
VALUES
	(2, 'cby', NULL),
	(3, 'ucu', NULL),
	(4, 'cafealt', NULL),
	(5, 'twitter', NULL),
	(6, 'email', NULL),
	(7, 'internet', NULL);
INSERT INTO `user` (`id`,`name`,`username`,`hashed_pass`,`language`,`student_num`,`email`,`twitter`,`cell`,`child_name`)
VALUES
	(1, 'admin', 'admin', SHA1('admin'), 'e', 0, 'admin@hvsi.ca', NULL, NULL, 'Admin'),
	(2, 'cby', 'cby', SHA1('cby'), 'e', 1, 'cby@hvsi.ca', NULL, NULL, 'Station'),
	(3, 'ucu', 'ucu', SHA1('ucu'), 'e', 2, 'ucu@hvsi.ca', NULL, NULL, 'Station'),
	(4, 'cafealt', 'cafealt', SHA1('cafealt'), 'e', 3, 'cafealt@hvsi.ca', NULL, NULL, 'Station'),
	(5, 'zombie_twitter', 'zombie_twitter', SHA1('zombie_pass'), 'e', 4, 'HumanVSInfected@twitter.com', NULL, NULL, 'Station'),
	(6, 'zombie_email', 'zombie_email', SHA1('zombie_pass'), 'e', 5, 'tag@hvsi.ca', NULL, NULL, 'Station'),
	(7, 'zombie_internet', 'zombie_internet', SHA1('zombie_pass'), 'e', 6, 'internet@hvsi.ca', NULL, NULL, 'Station');
INSERT INTO `post` (`id`,`time`,`title_e`,`title_f`,`content_e`,`content_f`,`allow_comments`)
VALUES
	(1, '2010-10-10 10:10:10', 'Home', 'French Title', '**What is HvsI?** Humans vs Infected is a week-long game of zombie-themed tag played at the University of Ottawa. Follow the links above to learn more!\n\n**How to play?** Just register online now or at a registration table (CBY, UCU or CafÃ© Alt) on Nov 1 or 2. There is a 5$ late fee to register on Tuesday. The game lasts from Monday @9AM to Friday @8PM.\n', 'French Content', 0),
	(2, '2010-10-20 13:46:49', 'Missions', '', '### General Missions\n**Bounties:** Put prizes as bounties on people (Alan Rock, Tyler Steeves, Claude LagÃ¼e, GG Mascott)\n**Picture List:**: Take pictures of yourself in HvsI t-shirt with a severed limb all around Ottawa.\n\n### Events\n**Military Containment:** The Military protects socks by firing nerf guns at Zombies. If Zombies or Humans get to the socks stash unharmed, they gain 5 socks.\n\n- *Location:* CBY lawn\n- *Time:* Tuesday @ 12:30PM\n\n**Rescue the Scientist:** Humans must rescue the Scientist, held captive by Zombies. Participants gain 5 socks. If the Scientist is freed, there is hope for a cure.\n\n- *Location:* TBD\n- *Time:* Wednesday @ 6PM\n\n**Mall Zombie Raid:** Zombies invade the Rideau Centre and videotape themselves performing the Thriller dance. Participants gain 5 socks.\n\n- *Location:* Rideau Centre\n- *Time:* Saturday @ 3PM\n\n**Amazing Race:** Humans start at UCU, follow the hints, avoid the Zombies.\n\n**Protect the Prime Minister:** Humans walk around Market protecting \"The President\"\n\n**End Game:** Minute to win it', '', 0),
	(3, '2010-10-20 13:51:41', 'Party', '', 'The closing ceremonies will be held at the [Parliament Ultraclub](http://www.facebook.com/event.php?eid=147647435280401) on November 5th and will start at 8PM', '', 0),
	(4, '2010-10-20 13:52:54', 'Rules', '', '**Every participant must read the rules before the game**\n\n**What\'s a tag?** A tag is a respectful touch by a Zombie\'s hand to a Human\'s body\n\n**Bandanna:** All participants must prominently display the appropriately coloured bandanna (provided) on their head, neck or arm at all times during the game.\n\n**Safe Zones:** Zombies cannot tag Humans while they are in safe zones. The game is frozen for 30 seconds after a Human leaves a safe zone. The following areas are designated safe zones:\n\n- Bathrooms\n- Any Office (eg: Prof, Peer Help Center, Protection, dentist, etc.)\n- Classrooms\n- Quiet Study Rooms and Library\n- SITE + UCU Cafeterias\n- Tape-delimited areas around registration tables (CBY, UCU, CafÃ© Alt)\n- 1848\n\n**Boundaries:** The game has no geographical boundaries. Extra points for a tag in another country!\n\n### Human Rules\n\n**Game Card:** Humans must keep their game card (provided) on them at all times.\n\n**Check Ins:** Humans must physically check in at a check-in table twice a day, with at least 4 hours between check-ins. Failure to do this will result in becoming a Zombie.  Participants can check-in online once during the week.\n\n**Check-in Locations:** CBY Basement, UCU Couch Lounge, CafÃ© Alt from 9AM to 5PM\n\n**Tagged By a Zombie:** When tagged by a Zombie, a Human is required to give the Zombie their game card. You automatically become a Zombie when the Zombie reports the tag, but you can only start tagging once you\'ve exchanged your white bandanna for a green one at a check-in location.\n\n**Stunning a Zombie:** You can throw/wield an official HvsI sock\n\n### Zombie Rules\n\n**Tagging:** When a Zombie tags a Human, the Zombie must take their victim\'s game card and report the tag asap using one of the following methods:\n\n- Email tag@HvsI.ca with the victim\'s game ID as the subject and using the email address used in registration\n- Tweet the victim\'s game ID with the #HvsI2010 hashtag (using the twitter account in your profile)\n- In person at a participating student association\'s office\n- Online at www.HvsI.ca by clicking the \"Report Tag\" button\n\n**Getting Stunned:** When hit with an official IEEE sock by a Human (Or a Nerf gun dart from Military), a Zombie is stunned for 2 minutes. A stunned zombie may not interact with the game in any way. This includes shielding other zombies from socks or following a human. The Zombie keeps the sock.\n\n', '', 0);
